### ISSUE TITLE
redis 存储的认证信息 timeout 默认值是-1，导致数据堆积。

### ISSUE THREAD

**Issue by clfsoft** [vains-Sofia/authorization-example#2]
下面的代码如果用户设置的timeout都是不到1分钟。那么 between 就变成0。实质上变成无期限了。
而且代码角度无期限的东西都是不太好的，如果最后的最大值还是0或者-1，
那么将timeout设置成30min（id token的默认值）或者60min（refresh token的默认值）。
```
            // 计算时间差
            Duration between = Duration.between(Instant.now(), maxInstant.get());
            // 转为分钟
            maxTimeout = between.toMinutes();
```

https://github.com/vains-Sofia/authorization-example/blob/e597bd122d0c23c15ad256e59572011a4d9509bc/authorization-server/src/main/java/com/example/service/impl/RedisOAuth2AuthorizationService.java#L105

**Comment by vains-Sofia** [comment]
> 下面的代码如果用户设置的timeout都是不到1分钟。那么 between 就变成0。实质上变成无期限了。 而且代码角度无期限的东西都是不太好的，如果最后的最大值还是0或者-1， 那么将timeout设置成30min（id token的默认值）或者60min（refresh token的默认值）。
> 
> ```
>             // 计算时间差
>             Duration between = Duration.between(Instant.now(), maxInstant.get());
>             // 转为分钟
>             maxTimeout = between.toMinutes();
> ```
> 
> https://github.com/vains-Sofia/authorization-example/blob/e597bd122d0c23c15ad256e59572011a4d9509bc/authorization-server/src/main/java/com/example/service/impl/RedisOAuth2AuthorizationService.java#L105

这种情况出现的几率基本为0，因为我是从几个token中找出最大值，然后跟现在时间进行计算得到的，如果说所有token(access_token、refresh_token、user_code等)的最大过期时间还不到1分钟那要不就是异常数据，要不就是及其特殊的业务需求，如果是特殊的业务需求就可以修改默认的最大时间了，就像你说的30分钟或者60分钟。

**Comment by clfsoft** [comment]
主要设置永不过期的数值。感觉不太好。

**Comment by vains-Sofia** [comment]
> 主要设置永不过期的数值。感觉不太好。

一般来说不会的，如果实在担心的话就改一下这一行的默认值。
https://github.com/vains-Sofia/authorization-example/blob/master/authorization-server/src/main/java/com/example/service/impl/RedisOAuth2AuthorizationService.java#L65
