### ISSUE TITLE
RedisOperator getHashAll的bug

### ISSUE THREAD

**Issue by clfsoft** [vains-Sofia/authorization-example#3]
下面代码不对
```
    public <T> T getHashAll(String key, Class<T> clazz) {
        Map<String, Object> entries = hashOperations().entries(key);
        if (ObjectUtils.isEmpty(entries)) {
            return null;
        }
        return JsonUtils.objectCovertToObject(entries, clazz);
    }
```
1.泛型根本没有用到
2.return JsonUtils.objectCovertToObject(`entries, clazz`);       
 ->   return JsonUtils.objectCovertToObject(`entries,Map.class,String.class, clazz`)
setHashAll就已经这么用了
```
   public void setHashAll(String key, Object value) {
        Map<String, Object> map = JsonUtils.objectCovertToObject(value, Map.class, String.class, Object.class);
        hashOperations().putAll(key, map);
    }
```

https://github.com/vains-Sofia/authorization-example/blob/08654f4c3190b0ccccfb91e04f6ac32fe3e075f2/authorization-server/src/main/java/com/example/support/RedisOperator.java#L192

**Comment by vains-Sofia** [comment]
如果没有其它疑问稍后我会关闭该issue
